import { UserWithProfile, UserRole } from "@/contexts/AuthContext";

// Mock user data
export const mockUsers: UserWithProfile[] = [
  {
    id: "1",
    email: "john.doe@example.com",
    email_confirmed_at: new Date().toISOString(),
    phone: "123-456-7890",
    phone_confirmed_at: new Date().toISOString(),
    app_metadata: {},
    user_metadata: {},
    aud: "authenticated",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    role: "student" as UserRole,
    name: "John Doe",
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: "2",
    email: "jane.smith@example.com",
    email_confirmed_at: new Date().toISOString(),
    phone: "098-765-4321",
    phone_confirmed_at: new Date().toISOString(),
    app_metadata: {},
    user_metadata: {},
    aud: "authenticated",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    role: "instructor" as UserRole,
    name: "Jane Smith",
    avatar: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: "3",
    email: "admin@example.com",
    email_confirmed_at: new Date().toISOString(),
    phone: "111-222-3333",
    phone_confirmed_at: new Date().toISOString(),
    app_metadata: {},
    user_metadata: {},
    aud: "authenticated",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    role: "admin" as UserRole,
    name: "Admin User",
    avatar: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: "4",
    email: "superadmin@example.com",
    email_confirmed_at: new Date().toISOString(),
    phone: "444-555-6666",
    phone_confirmed_at: new Date().toISOString(),
    app_metadata: {},
    user_metadata: {},
    aud: "authenticated",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    role: "super_admin" as UserRole,
    name: "Super Admin",
    avatar: "https://i.pravatar.cc/150?img=4",
  },
];
