
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acmfhyqvqdhnmmnblrdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjbWZoeXF2cWRobm1tbmJscmRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjYyNjYsImV4cCI6MjA2MTAwMjI2Nn0.t9RxZyDeSvYcFxSfJRGcg_FPIHAcHF2f3ON_j1hh9kY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
